import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/theme-toggle";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable} dark`}>
      <body>
        <ThemeProvider
          storageKey="testing-poc-theme"
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <ModeToggle></ModeToggle>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
